### PR TITLE
9.7 profile page bugfixes & enhancing

### PR DESCRIPTION
**Pull request by mbareeva**
- deleted data that not needed anymore (breadcrumbs, about me description)
- for job offer detailed page header added

### CODE REVIEW

**Comment by ellakatajisto** [comment]
looks good! i run the app and checked the code, everything is looking good to me :)

**Review by ellakatajisto — APPROVED** [review]
looks good! i run the app and checked the code, everything is looking good to me :)

**Comment by lyrated** [comment]
@mbareeva IF you have time, can you merge this instead of Josh and fix the formatting of the ejs files? XD
But, as you know already, this is just a personal preference and not important!

**Comment by mbareeva** [comment]
> @mbareeva IF you have time, can you merge this instead of Josh and fix the formatting of the ejs files? XD
> But, as you know already, this is just a personal preference and not important!

sure, will try to fix it! thanks!

**Pull request merged**
