### PR TITLE
6.2 fix be + 7.4 connect questionnaire with BE

### PR DESCRIPTION
**Pull request by joshuameiser**
I wasn't able to actually test the functions yet since we I don't have the front end necessary for that.
I replaced the two methods with ones that have hardcoded data. With that one everything that's not dependant on the front-end input seems to work.

### CODE REVIEW

**Comment by mbareeva** [comment]
@joshuameiser I saw on top that you want to compare your branch with main, are you sure?

**Comment by joshuameiser** [comment]
> @joshuameiser I saw on top that you want to compare your branch with main, are you sure?

Ahh thanks, no I did not mean to do that :D

**Comment by lyrated** [comment]
Kim + I changed the following:
- two different links for signups for recruiter & candidate
- questionnaire is the first form to be viewed, then it redirects to user signup
- TODO?: right now after submitting the questionnaire, a candidate / job offer will be created and saved in our DB. But in case the user doesn't sign up (with email and password), this candidate/job offer will still be in the DB + ES. we can leave it like this or handle it accordingly (-> how?)
- questionnaire is connected with DB, also with the bootstrap tags input
- a "description" field was added to the candidate
- work_experience was deleted
- routes were slightly changed

**Comment by ellakatajisto** [comment]
looks nice, good job :) i didn't look that much into the code yet but seems to work well, from what i see safe to merge, apparently there are no conflicts either. 

here are some remarks, i think most of them don't have that much to do with your tasks directly but i'll write them down so i don't forget: 

- the signup page where the user lands after filling out the form could include something that catches the eye like "one step left, sign up now to see your matches!" bc i personally was confused for a bit (was too lazy to read the small text at first), i thought i did something wrong and landed in the login page, redesigning it could be a small new task for someone :) 

- i liked the new wordings you came up with! a couple questions could still use a better wording (in the work culture and soft skill part the "least important" category is truly tricky, maybe you already thought about it)
Näyttökuva 2020-1-3 kello 21 02 08
Näyttökuva 2020-1-3 kello 21 19 03

- when typing the keywords that become tags in the form, if you press comma between the words the tag is created but the comma stays (and goes into the next keyword if not deleted), maybe we figure out a way to fix that in the future 
Näyttökuva 2020-1-3 kello 21 01 19

**Pull request merged**
