### PR TITLE
5.3d questionaires page

### PR DESCRIPTION
**Pull request by simbuzan**
- set up questionnaire page for candidate and job offer
- questions with dropdowns and checkboxes
- questions with input tags
- questions categorized by importance
- carousel pages
- fixed indicator controls

### CODE REVIEW

**Review by lyrated — APPROVED** [review]
Looking through the changes is really difficult since you have all the commits from other branches as well... I guess because you did a rebase instead of merge? Anyway, that's why I didn't really look here on github but just roughly in VS code. **You can merge** imo, even if there are a few things that should be changed, but I can do that with Kim during our current ticket!
-> The inputs should have the attribute "required". Also, even though the carousel is super nice, it has a huge usability disadvantage when I tried it out (I hit ENTER to get to the next question but the page just hung because it tried to submit the form instead and not all required fields were submitted). So maybe it will be better to split it up into different pages :/ or if we have time, create a multistep form with javascript (lots of tutorials out there so maybe just copy+paste code). Also, on the candidate view, the hints are still a placeholder so we'll change that too

**Comment by kimc0de** [comment]
Hey Ly, thanks for the comments. We did pull rebase from development. There're conflicts but I can resolve them to merge. Or we can just keep working on this branch for the 7.4 connect questionnaires with the backend?
About the Enter button, you're right the page will hang. We just managed to avoid it with the questions that have input tags... We can add the js files for the page to avoid submitting with Enter.. Or you think the multiple-step form is better?

**Comment by lyrated** [comment]
Hmm I told Josh already that we'll continue using his branch, since he worked on the Backend and left some comments and so on. As soon as all the merges are through, we can use his branch and merge the new changes from development to it, so basically that's the same as working with your branch anyway 👍 
So best to simply merge this one and delete the branch, then we'll continue on 6.2-Fix-BE or whatever it's called :)

For changing the carousel... we have different options.
1. Leave it as it is and pretend "that's not our MVP"
2. Put everything vertically without pagers / javascript
3. Add some custom javascript to solve the problems (also it's not really good that you can come back to the first question after the last question, so we would need to change a lot... and why use this bootstrap plugin just to change almost everything, when we can simply use another method)
4. So last alternative is using a multistep form.
Tbh our focus is on the **actual** ticket, connecting the backend, and after that we can decide what to do. Maybe we do have some time left then or else it would be a new ticket :)

**Comment by kimc0de** [comment]
ok I just resolved the conflicts.. the conflicts were so werid cuz they just look the same as in development but github marked as conflicts @@
We can merge now

**Pull request merged**
